### ISSUE TITLE
No-longer builds with openMPI 1.1.x

### ISSUE THREAD

**Issue by Luke-Nukem** [bsteinb/rsmpi#22]
I haven't had time to check much further, but it seems rsmpi no-longer builds with openMPI 1.1.6/7

```
src/ffi/rsmpi.h:32:14: error: unknown type name 'MPI_Message', err: true
src/ffi/rsmpi.h:33:14: error: unknown type name 'MPI_Message', err: true
```

Just the above error. I compiled and installed openMPI 2.2.1 from source, and rsmpi builds fine. I'll be submitting a PR to update openSUSE to use 2.2.1 soon so hopefully this will become a non-issue (for openSUSE at least).

**Comment by bsteinb** [comment]
> I haven't had time to check much further, but it seems rsmpi no-longer builds with openMPI 1.1.6/7

I don't think it ever did. The OpenMPI 1.1 branch was created in 2006, predating not only the MPI 3.1 specification that `rsmpi` currently targets by almost a decade, but also 3.0, 2.2 and even 2.1. That is why the `MPI_Message` type that `rsmpi` expects is missing from your `mpi.h`.

At the moment I do not have plans to work on supporting older versions of the MPI specification. 3.0 should be possible, but anything older becomes a hassle, because `const`ness in the MPI API was only cleaned up then.

**Comment by Luke-Nukem** [comment]
@bsteinb better edit the line in the Readme; "OpenMPI 1.10.7, 2.0.2, 2.1.1". Not quite something to do a PR for.

 :smiley:

**Comment by bsteinb** [comment]
You can edit and make a PR on the web, AFAIK. No need for the full fork clone push PR cycle. 

Honestly, I am not sure how you want me to change that line. Maybe I am reading it differently, but to me it does not claim that rsmpi should work with OpenMPI 1.1.X.

**Comment by Luke-Nukem** [comment]
> rsmpi is currently tested with these implementations:
> OpenMPI 1.10.7, 2.0.2, 2.1.1

Maybe I misunderstand? The above implies to me that rsmpi builds with those versions - I was suggesting removing v1.10.x from the list. Or does that mean it works with the v1.10.x libraries even though it won't build with them?

I won't do a PR unless I'm sure I understand it :)

**Comment by bsteinb** [comment]
Ah, I think I get where the confusion is coming from. In the title of this issue you referenced "openMPI 1.1.x" and then in the description stated

> rsmpi no-longer builds with openMPI 1.1.6/7

which lead me to believe you were having trouble building `rsmpi` against the ancient 1.1.X branch of OpenMPI, which, as I said would not surprise me. I only now noticed, that there is no 1.1.6 nor a 1.1.7, so I assume you are indeed talking about the more recent 1.10.6 and 1.10.7.

In that case, I am still not sure what is going on. 1.10.7 works fine for me, have a look at the Travis CI results which are based on a standard installation of OpenMPI 1.10.7. Maybe openSUSE disables some options in their packages of OpenMPI that would cause the MPI_Message type to be absent from the headers?

**Comment by bsteinb** [comment]
Could you clarify which version of OpenMPI you are having trouble with?

**Comment by Luke-Nukem** [comment]
I suspect it's an issue with the openSUSE packaged version. I'll be pushing an update for the lastest version soon and will investigate the issue a bit further then.

Until then I think it's best to close this. I think I've pretty much nailed the use of rsmpi in my Game of Life 👍

**Comment by bsteinb** [comment]
Alright, we can close this issue if you want to, but I would still like to know what is going on. Could you tell me what version of openSUSE you used and where you got the OpenMPI packages from so I can try to reproduce this?

**Comment by Luke-Nukem** [comment]
Sure, the package is [here](https://build.opensuse.org/package/show/science:HPC/openmpi), the `%build` section in the spec shows the configure args used.

I use openSUSE Tumbleweed.

**Comment by bsteinb** [comment]
I had a look at the package and it installs an `mpi.h` header that *does* define the `MPI_Message` type. I tried to reproduce the error in a VM, but I was able to successfully build `rsmpi` after installing the OpenMPI package you referenced plus `clang` and `libclang`. Could it be that there is an older version of the OpenMPI package lying around on your system which the `rsmpi` build process picks up?

Could you send the output of `mpicc -show` and `ompi_info | head -n 50` on your system?
