### ISSUE TITLE
failure to compile with OpenMPI 4.0 due to removed symbols

### ISSUE THREAD

**Issue by ExpHP** [bsteinb/rsmpi#64]
```rust
error[E0425]: cannot find function `MPI_Type_hvector` in module `ffi` 
  --> /home/cc/.cargo/registry/src/github.com-1ecc6299db9ec823/mpi-0.5.4/src/datatype.rs:212:18 
   | 
212 |             ffi::MPI_Type_hvector(count, blocklength, stride, oldtype.as_raw(), &mut newtype); 
   |                  ^^^^^^^^^^^^^^^^ did you mean `MPI_Type_vector`? 

error: aborting due to previous error
```

OpenMPI 4.0 (which recently landed on arch) removes some symbols that were eliminated from the MPI standard 3.0.

https://www.open-mpi.org/faq/?category=mpi-removed

**Comment by AndrewGaspar** [comment]
Ah, I think this was just overlooked. It looks like `MPI_Type_create_hvector` has been present since MPI-2. Fix incoming.

**Comment by bsteinb** [comment]
Ugh indeed. Thanks for reporting this.

**Comment by aromazyl** [comment]
How to resolve it fininally?

**Comment by ExpHP** [comment]
This is fixed in master, a new version just needs to be released.

Browsing around, it seems that may currently be blocked on #54? (see #67)

---

If you are writing an application, you can depend on mpi as a git dependency:

```rust
[dependencies]
mpi = { git = "https://github.com/bsteinb/rsmpi", rev = "f9aec8b8d82" }
```

However, this is a bad idea for libraries that want to be published on crates.io.  In that case, you should stick to the current v0.5.x release, and users will need to not use an MPI implementation that isn't OpenMPI 4.x.  (they can [build OpenMPI 3.1.4 from source](https://www.open-mpi.org/software/ompi/v3.1/))

**Comment by frqc** [comment]
It seems the problem still exists and the workaround still works. But when will the new version be published btw?

**Comment by QuarticCat** [comment]
Why not cherry-pick this solution and release a small version update? We've been waiting for a new version for too long. Before the coming of 0.6, you can actually keep updating 0.5.

**Comment by jedbrown** [comment]
There are semver-incompatible changes. I'm hoping to get an hour or so to tie up loose ends and release v0.6 in the near future. https://github.com/rsmpi/rsmpi/issues/95
